1. What is the relationship between tobacco use and physical activity 


```{r}
tobacco_data <- new_youth_risk_df %>% 
  filter(Topic %in% c("Tobacco Use")) %>% 
  group_by(ShortQuestionText) %>%
  summarise(Sample_Size, Greater_Risk_Data_Value, Lesser_Risk_Data_Value, Race, SexualIdentity, Topic, Grade, SexOfSexualContacts, Sex)
```

```{r}
tobacco_data %>% 
  filter(Race == "Total", SexualIdentity == "Total", SexOfSexualContacts == "Total", Sex == "Total") %>%
filter (Grade != "Total") %>%
group_by(ShortQuestionText) %>%
  mutate(summarised_group = case_when(ShortQuestionText %in% c("Frequent electronic vapor product use", "Electronic vapor product use",  "Electronic vapor products from store", "Frequent smokeless tobacco use", "Current smokeless tobacco use", "Current electronic vapor product use") ~ "Vaporizer and Smokeless Tobacco Use",
         ShortQuestionText %in% c("Current daily electronic vapor product use", "Current cigarette, cigar, or smokeless tobacco use", "Current daily cigar use", "Current daily cigarette use", "Current daily smokeless tobacco use") ~ "Daily Nicotine Use", 
         ShortQuestionText %in% c("Smoked >10 cigarettes" ,"Frequent cigarette use", "Ever cigarette use","Current cigarette, cigar, or smokeless tobacco use","Current cigarette use" , "Current cigarette or cigar use", "Current tobacco use") ~ "Cigarette Use", 
         ShortQuestionText %in% c("Frequent cigar use","Current cigar use")~ "Cigar Use",
           TRUE ~ ShortQuestionText)) %>%
  mutate(Grade = fct_relevel(Grade, "9th")) %>%
  group_by(Grade, summarised_group) %>%
  summarise(Sum = sum(Sample_Size, na.rm = TRUE)) %>%
  ggplot(aes(y = (fct_relevel (summarised_group, "Daily Nicotine Use", "Cigar Use", "Vaporizer and Smokeless Tobacco Use", "Cigarette Use")), x = Sum, fill = Grade)) +
  geom_col(ledgend = NULL, position = "dodge")
```

```{r nicotine-use-by-grade, fig.alt = "Bar graph showing nicotine use by type of use and by grade, where Cigarette use is the highest, followed by vaporizer and smokeless tobacco, and finally cigar use. The graph shows that use of nicotine products trends upwards as students increase in grade. Daily nicotine use actoss all four grades is 5%."}

unique(tobacco_data$ShortQuestionText)

tobacco_data %>%
  filter(Grade != "Total") %>%
  mutate(Grade = as.factor(Grade)) %>%
  mutate(summarised_group = case_when(ShortQuestionText %in% c("Frequent electronic vapor product use", "Electronic vapor product use",  "Electronic vapor products from store", "Frequent smokeless tobacco use", "Current smokeless tobacco use", "Current electronic vapor product use") ~ "Vaporizer and Smokeless Tobacco Use",
         ShortQuestionText %in% c("Current daily electronic vapor product use", "Current cigarette, cigar, or smokeless tobacco use", "Current daily cigar use", "Current daily cigarette use", "Current daily smokeless tobacco use") ~ "Daily Nicotine Use", 
         ShortQuestionText %in% c("Smoked >10 cigarettes" ,"Frequent cigarette use", "Ever cigarette use","Current cigarette, cigar, or smokeless tobacco use","Current cigarette use" , "Current cigarette or cigar use", "Current tobacco use") ~ "Cigarette Use", 
         ShortQuestionText %in% c("Frequent cigar use","Current cigar use")~ "Cigar Use",
           TRUE ~ ShortQuestionText)) %>%
  mutate(Grade = fct_relevel(Grade, "9th")) %>%
  group_by(Grade, summarised_group) %>%
  summarise(mean = mean(Greater_Risk_Data_Value, na.rm = TRUE)) %>%
  ggplot(aes(y = (fct_relevel(summarised_group, "Daily Nicotine Use", "Cigar Use", "Vaporizer and Smokeless Tobacco Use", "Cigarette Use")), x = mean, fill = Grade)) +
  geom_col(ledgend = NULL, position = "dodge") +
  labs(x = "Percentage", y = "Category of Use",
    title = "Nicotine Use by Grade", "scale",
    fill = "Grade") +
  scale_fill_viridis_d(name="Grade",
                    breaks=c("12th", "11th", "10th", "9th"))

ggsave(filename = "smoking_data.png", height = 8, width = 12)

```



```{r}
health_data %>%
  filter(Grade != "Total") %>%
  mutate(Grade = as.factor(Grade)) %>%
  mutate(Grade = fct_relevel(Grade, "9th")) %>%
  group_by(Grade, ShortQuestionText) %>%
  summarise(mean = mean(Greater_Risk_Data_Value, na.rm = TRUE)) %>%
  ggplot(aes(y = fct_relevel (ShortQuestionText, "Television watching", "Computer use", "Daily physical activity",  "Daily PE attendance", "Physical activity >= 5 days", "Physical activity", "PE attendance"), x = mean, fill = Grade)) +
  geom_col(ledgend = NULL, position = "dodge") +
  labs(x = "Percentage", y = "Type of Activity ",
    title = "Physical Activity by Grade",
    fill = "Grade") +
  scale_fill_viridis_d (name="Grade",
                    breaks=c("12th", "11th", "10th", "9th"))

ggsave(filename = "health_data.png", height = 10, width = 10)

```

