---
title: Project title
author: by Ella and Leo
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(readr)
```

```{r load-data}
youth_risk <- read_csv("data/DASH_-_Youth_Risk_Behavior_Surveillance_System__YRBSS___High_School____Including_Sexual_Orientation_20240207.csv")

```

```{r load-new_youth_risk_df}
new_youth_risk_df <- youth_risk %>% 
  select("YEAR", "Topic", "Subtopic", "ShortQuestionText", "Greater_Risk_Data_Value", "Lesser_Risk_Data_Value", "Sample_Size", "Sex", "Race", "Grade", "SexualIdentity", "SexOfSexualContacts") %>%
  filter(YEAR == 2017)
```

```{r Alc_Race_data_frame}
Alc_Race_data_frame <- new_youth_risk_df %>%
  filter(ShortQuestionText %in% c("Initiation of alcohol use", "Ever alcohol use", "Current alcohol use", "Largest number of drinks")) %>%
  group_by(ShortQuestionText, Race) %>%
  summarise(Greater_Risk_Data_Value = round(mean(Greater_Risk_Data_Value, na.rm =TRUE), digits = 0), Sample_Size = Sample_Size, Sex, Grade, SexualIdentity, SexOfSexualContacts)%>%
   arrange(desc(Greater_Risk_Data_Value)) %>%
  filter(Sex == "Total", Grade == "Total", SexualIdentity == "Total", SexOfSexualContacts == "Total")


 Alc_Race_data_frame <- Alc_Race_data_frame %>%
 pivot_longer(
    ends_with("Risk_Data_Value"), 
    names_to = "Risk_Data", 
    values_to = "Risk_Percent")  
```

```{r Alc-Race-sample-size-segmented-bar-graph, fig.alt = "Bar chart of Risky behaviors in teen alcohol use by sample size of race. The questions being asked are: students who reported that the largest number of drinks they had in a row was 10 or more, students who had their first drink of alcohol before age 13 years, students who ever drank alcohol, students who currently drink alcohol, and the races counted are Black or African American, Asian, American Indian or Alaska Native, Multiple Race, Hispanic or Latino, White, and the total of all races. White students comprise the majority of this data at about 80% of the sample size with 6765-7015 respondents per question, and is massively underrepresented with only 17-19 respondents per question."}
Alc_Race_data_frame$Race <-  fct_relevel(Alc_Race_data_frame$Race, c("Native Hawaiian or Other Pacific Islander", "Black or African American", "Asian","American Indian or Alaska Native", "Multiple Race", "Hispanic or Latino", "White", "Total")) 

Alc_Race_data_frame %>% 
ggplot(aes(y= Race, x = Sample_Size, fill = ShortQuestionText)) +
   geom_col(position="dodge", stat="identity") +
labs(y = "Race", x = "Sample Size",
    title = "Risky Behaviors in Teen Alcohol Use",
    subtitle = "By Sample Size of Race",
    fill = "Severity") +
  scale_fill_viridis_d(name="Questions",
                     breaks=c("Largest number of drinks", "Initiation of alcohol use", "Ever alcohol use", "Current alcohol use"),
                     labels = c("Students who reported that the largest \nnumber of drinks they had in a row was 10 or more", "Students who had their first drink of \nalcohol before age 13 years", "Students who ever drank alcohol", "Students who currently drink alcohol"))+
  theme(legend.text=element_text(size=12))

ggsave(filename = "Alc_Race_sample_size.png", height = 8, width = 12)
```

```{r Alc-Race-segmented-bar-graph, fig.alt = "Bar chart of Risky behaviors in teen alcohol use by Race and Percentage engaging in risky behavoirs. The questions being asked are: students who reported that the largest number of drinks they had in a row was 10 or more, students who had their first drink of alcohol before age 13 years, students who ever drank alcohol, students who currently drink alcohol, and the races counted are Black or African American, Asian, American Indian or Alaska Native, Multiple Race, Hispanic or Latino, and White. Over half of all students except for Asian and Black or African American stunts have ever drunk alcohol. Binge drinking (Students who reported that the largest number of drinks they had in a row was 10 or more) is most common in Latino students and not represented in Asian students, between 10-23% of students had their first drink of alcohol before the age of 13, and between 7-29% of students currently drink alcohol."}
Alc_Race_data_frame$Race <-  fct_relevel(Alc_Race_data_frame$Race, c("Black or African American", "Asian", "American Indian or Alaska Native", "Multiple Race", "Hispanic or Latino", "White", "Total"))

Alc_Race_data_frame %>% 
  filter(Race != "Native Hawaiian or Other Pacific Islander") %>%
  filter(Race != "Total") %>%
ggplot(aes(y= Race, x = Risk_Percent, fill = ShortQuestionText)) +
   geom_col(position="dodge", stat="identity") +
labs(y = "Race", x = "Percentage",
    title = "Risky Behaviors in Teen Alcohol Use",
    subtitle = "By Race",
    fill = "Severity") +
  scale_fill_viridis_d(name="Questions",
                     breaks=c("Largest number of drinks", "Initiation of alcohol use", "Ever alcohol use", "Current alcohol use"),
                     labels = c("Students who reported that the largest \nnumber of drinks they had in a row was 10 or more", "Students who had their first drink of \nalcohol before age 13 years", "Students who ever drank alcohol", "Students who currently drink alcohol")) +
  theme(legend.text=element_text(size=12))

ggsave(filename = "Alc_Race.png", height = 8, width = 12)
```

```{r Alc_Grade_data_frame}
Alc_Grade_data_frame <- new_youth_risk_df %>%
  filter(ShortQuestionText %in% c("Initiation of alcohol use", "Ever alcohol use", "Current alcohol use", "Largest number of drinks")) %>%
  group_by(ShortQuestionText, Grade) %>%
  summarise(Greater_Risk_Data_Value = round(mean(Greater_Risk_Data_Value, na.rm =TRUE), digits = 0), Sample_Size = Sample_Size, Sex, Race, SexualIdentity, SexOfSexualContacts) %>%
    filter(Sex == "Total", Race == "Total", SexualIdentity == "Total", SexOfSexualContacts == "Total")

 Alc_Grade_data_frame <- Alc_Grade_data_frame %>%
 pivot_longer(
    ends_with("Risk_Data_Value"), 
    names_to = "Risk_Data", 
    values_to = "Risk_Percent") 
    # filter(Grade != "Total", Sex != "Total")
```
```{r Alc-Grade-sample-size-segmented-bar-graph, fig.alt = "Bar chart of Risky behaviors in teen alcohol use by sample size of Grade. The questions being asked are: students who reported that the largest number of drinks they had in a row was 10 or more, students who had their first drink of alcohol before age 13 years, students who ever drank alcohol, students who currently drink alcohol, and the grades counted are 9th, 10th, 11th, 12th, and the total of all grades. The number of respondents goes up slightly as the grades increase."}
Alc_Grade_data_frame$Grade <-  fct_relevel(Alc_Grade_data_frame$Grade,  c("9th", "10th", "11th", "12th", "Total"))

Alc_Grade_data_frame %>% 
ggplot(aes(y= Grade, x = Sample_Size, fill = ShortQuestionText)) +
   geom_col(position= "dodge", stat= "identity") +
labs(y = "Grade", x = "Sample Size",
    title = "Risky Behaviors in Teen Alcohol Use",
    subtitle = "By Sample Size of Grade",
    fill = "Severity") +
  scale_fill_viridis_d(name="Questions",
                     breaks=c("Largest number of drinks", "Initiation of alcohol use", "Ever alcohol use", "Current alcohol use"),
                     labels = c("Students who reported that the largest \nnumber of drinks they had in a row was 10 or more", "Students who had their first drink of \nalcohol before age 13 years", "Students who ever drank alcohol", "Students who currently drink alcohol"))+
  theme(legend.text=element_text(size=12))

 ggsave(filename = "Alc_Grade_sample_size.png", height = 8, width = 12)

```

```{r Alc_Grade-segmented-bar-graph, fig.alt = "Bar chart of Risky behaviors in teen alcohol use by Grade and Percentage engaging in risky behaviors. The questions being asked are: students who reported that the largest number of drinks they had in a row was 10 or more, students who had their first drink of alcohol before age 13 years, students who ever drank alcohol, students who currently drink alcohol, and the grades counted are 9th, 10th, 11th, and 12th. The percentage of students engaging in risky behavior increased with each grade."}
Alc_Grade_data_frame$Grade <-  fct_relevel(Alc_Grade_data_frame$Grade, c("9th", "10th", "11th", "12th", "Total"))

Alc_Grade_data_frame %>% 
  filter(Grade != "Native Hawaiian or Other Pacific Islander") %>%
  filter(Grade != "Total") %>%
ggplot(aes(y= Grade, x = Risk_Percent, fill = ShortQuestionText)) +
   geom_col(position="dodge", stat="identity") +
 labs(y = "Grade", x = "Percentage",
    title = "Risky Behaviors in Teen Alcohol Use",
    subtitle = "By Grade",
    fill = "Severity") +
  scale_fill_viridis_d(name="Questions",
                     breaks=c("Largest number of drinks", "Initiation of alcohol use", "Ever alcohol use", "Current alcohol use"),
                     labels = c("Students who reported that the largest \nnumber of drinks they had in a row was 10 or more", "Students who had their first drink of \nalcohol before age 13 years", "Students who ever drank alcohol", "Students who currently drink alcohol"))+
  theme(legend.text=element_text(size=12))

 ggsave(filename = "Alc_Grade.png", height = 8, width = 12)

```
```{r Sex_Race_data_frame}
Alc_Sex_data_frame <- new_youth_risk_df %>%
  filter(ShortQuestionText %in% c("Initiation of alcohol use", "Ever alcohol use", "Current alcohol use", "Largest number of drinks")) %>%
  group_by(ShortQuestionText, Sex) %>%
  summarise(Greater_Risk_Data_Value = round(mean(Greater_Risk_Data_Value, na.rm =TRUE), digits = 0), Sample_Size = Sample_Size, Grade, Race, SexualIdentity, SexOfSexualContacts) %>%
    filter(Grade == "Total", Race == "Total", SexualIdentity == "Total", SexOfSexualContacts == "Total")

 Alc_Sex_data_frame <- Alc_Sex_data_frame %>%
 pivot_longer(
    ends_with("Risk_Data_Value"), 
    names_to = "Risk_Data", 
    values_to = "Risk_Percent") 
    # filter(Grade != "Total", Sex != "Total")
```
```{r Alc-Sex-sample-size-segmented-bar-graph, fig.alt = "Bar chart of Risky behaviors in teen alcohol use by sample size of sex. The questions being asked are: students who reported that the largest number of drinks they had in a row was 10 or more, students who had their first drink of alcohol before age 13 years, students who ever drank alcohol, students who currently drink alcohol, and the sexes counted are male, female, and the total of the sexes. The sample size of females is slighly higher than that of males."}
Alc_Sex_data_frame$Sex <-  fct_relevel(Alc_Sex_data_frame$Sex, c("Female","Male", "Total"))

Alc_Sex_data_frame %>% 
ggplot(aes(y= Sex, x = Sample_Size, fill = ShortQuestionText)) +
   geom_col(position= "dodge", stat= "identity") +
labs(y = "Sex", x = "Sample Size",
    title = "Risky Behaviors in Teen Alcohol Use",
    subtitle = "By Sample Size of Sex",
    fill = "Severity") +
  scale_fill_viridis_d(name="Questions",
                     breaks=c("Largest number of drinks", "Initiation of alcohol use", "Ever alcohol use", "Current alcohol use"),
                     labels = c("Students who reported that the largest \nnumber of drinks they had in a row was 10 or more", "Students who had their first drink of \nalcohol before age 13 years", "Students who ever drank alcohol", "Students who currently drink alcohol"))+
  theme(legend.text=element_text(size=12))

 ggsave(filename = "Alc_Sex_sample_size.png", height = 8, width = 12)

```

```{r Alc_Sex-segmented-bar-graph, fig.alt = "Bar chart of Risky behaviors in teen alcohol use by Sex and Percentage engaging in risky behaviors. The questions being asked are: students who reported that the largest number of drinks they had in a row was 10 or more, students who had their first drink of alcohol before age 13 years, students who ever drank alcohol, students who currently drink alcohol, and the sexes counted are male and female. The percentage of female students engaging in risky behavior is higher than males students."}
Alc_Sex_data_frame %>% 
  filter(Sex != "Native Hawaiian or Other Pacific Islander") %>%
  filter(Sex != "Total") %>%
ggplot(aes(y= Sex, x = Risk_Percent, fill = ShortQuestionText)) +
   geom_col(position="dodge", stat="identity") +
 labs(y = "Sex", x = "Percentage",
    title = "Risky Behaviors in Teen Alcohol Use",
    subtitle = "By Sex",
    fill = "Severity") +
  scale_fill_viridis_d(name="Questions",
                     breaks=c("Largest number of drinks", "Initiation of alcohol use", "Ever alcohol use", "Current alcohol use"),
                     labels = c("Students who reported that the largest \nnumber of drinks they had in a row was 10 or more", "Students who had their first drink of \nalcohol before age 13 years", "Students who ever drank alcohol", "Students who currently drink alcohol"))+
  theme(legend.text=element_text(size=12))

 ggsave(filename = "Alc_Sex.png", height = 8, width = 12)

```

```{r old-atempts}
# Alc_data_frame %>% 
#   ggplot(aes(x= ShortQuestionText, y = Risk_Percent, fill = Race))+
#   geom_col(position = "dodge") +
#   facet_wrap(~Risk_Data) +
#   scale_fill_brewer(palette = "RdPu")
```

